server {
    listen 80;
    server_name localhost;

    location /self_care_bingo/ {
        alias /usr/share/nginx/html/self_care_bingo/;
        try_files $uri $uri/ /self_care_bingo/index.html;
    }

    error_page 404 /self_care_bingo/index.html;

    location = / {
        return 301 /self_care_bingo/;
    }
}
